## **Step 1: Data Preprocessing**

Data preprocessing is the process of cleaning and preparing raw data so that it can be used effectively for data analysis and machine learning tasks. High-quality data is essential because poor or inconsistent data can lead to inaccurate analysis and unreliable machine learning results.

The primary objective of data preprocessing is to improve data quality by:
- Handling missing values  
- Removing noise and inconsistencies  
- Transforming data into a suitable and structured format  

These steps ultimately enhance the accuracy, reliability, and performance of analytical models and machine learning algorithms. As part of this process, attributes that were irrelevant to the objectives of this project were removed.

### **1.1 Selected Attributes After Removing Irrelevant Features**

After eliminating unnecessary attributes, the following features were retained for further processing and analysis:

1. **Student_ID**
2. **First_Name**
3. **Last_Name**
4. **Email**
5. **Gender**
6. **Age**
7. **Department**
8. **Attendance (%)**
9. **Midterm_Score**
10. **Participation_Score**
11. **Projects_Score**
12. **Final_Score**
13. **Assignments_Avg**
14. **Quizzes_Avg**
15. **Total_Score**
16. **Grade**

In [1]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import joblib

dataFile = pd.read_csv("ProcessedStudentDataFile.csv")
dataFile.head()

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade
0,S1000,Omar,Williams,student0@university.com,Female,22,Engineering,52.29,55.03,57.82,84.22,74.06,3.99,85.90,56.09,F
1,S1001,Maria,Brown,student1@university.com,Male,18,Engineering,97.27,97.23,45.80,NaN,94.24,8.32,55.65,50.64,A
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Business,57.19,67.05,93.68,67.70,85.70,5.05,73.79,70.30,D
3,S1003,Omar,Williams,student3@university.com,Female,24,Mathematics,95.15,47.79,80.63,66.06,93.51,6.54,92.12,61.63,A
4,S1004,John,Smith,student4@university.com,Female,23,CS,54.18,46.59,78.89,96.85,83.70,5.97,68.42,66.13,F

### **1.2 Identifying Missing Values**

In this step, missing values in the dataset are identified directly within the notebook. Identifying missing data is an important part of data preprocessing, as incomplete values can negatively affect statistical analysis and machine learning model performance.

The dataset is examined column by column to check whether any attribute contains null (missing) values. Whenever missing values are detected, the corresponding column is identified for further processing.

Based on this analysis, the following columns were found to contain missing data:

1. **Attendance (%)**
2. **Assignments_Avg**

In [2]:
totalColumns = len(dataFile.columns)
i = 0
while i < totalColumns:
    columnName = dataFile.columns[i]
    if dataFile[columnName].isnull().any():
        print(columnName, "column has null values")
    i += 1
dataFile.head()

Attendance (%) column has null values
Assignments_Avg column has null values

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade
0,S1000,Omar,Williams,student0@university.com,Female,22,Engineering,52.29,55.03,57.82,84.22,74.06,3.99,85.90,56.09,F
1,S1001,Maria,Brown,student1@university.com,Male,18,Engineering,97.27,97.23,45.80,NaN,94.24,8.32,55.65,50.64,A
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Business,57.19,67.05,93.68,67.70,85.70,5.05,73.79,70.30,D
3,S1003,Omar,Williams,student3@university.com,Female,24,Mathematics,95.15,47.79,80.63,66.06,93.51,6.54,92.12,61.63,A
4,S1004,John,Smith,student4@university.com,Female,23,CS,54.18,46.59,78.89,96.85,83.70,5.97,68.42,66.13,F

## **1.3  Deciding How to Fill Missing Values**

After identifying the columns with missing values, the next step is to decide how these missing entries should be filled. Two common statistical approaches are considered:

- Using the **mean** of the column  
- Using the **median** of the column  

To make this decision, the distribution of the data is analyzed by comparing the mean and median values of each affected column. This comparison helps determine whether the data is evenly distributed or skewed.

If the mean and median values are close to each other, it indicates that the data is approximately symmetric and not heavily influenced by outliers. In such cases, using the mean is considered appropriate. However, if there is a large difference between the mean and median, the data is likely skewed, and the median becomes a better choice.

For the columns with missing values, both the mean and median were calculated and compared. Since the values were found to be very similar, it was concluded that the data is not significantly skewed. Therefore, the **mean** was selected as a suitable method for filling the missing values.

---

### **1.3.1 Statistical Analysis of Missing Value Columns**

To perform this analysis, the **mean** and **median** of the columns containing missing values were calculated directly within the notebook. This comparison helps in understanding the distribution of the data and determining whether it is skewed or approximately symmetric.

#### Attendance (%)
- **Mean:** 75.4314  
- **Median:** 75.725  

#### Assignments_Avg
- **Mean:** 74.7987  
- **Median:** 74.81  

Since the mean and median values for both columns are very close to each other:

- 75.4314 ≈ 75.725  
- 74.7987 ≈ 74.81  

this indicates that the data is **not significantly dispersed** and does not show noticeable skewness. Therefore, **either the mean or median can be safely used** to fill the missing values.

In [3]:
attendanceColumn = pd.to_numeric(dataFile['Attendance (%)'], errors='coerce').dropna()
print("Attendance Mean:", np.mean(attendanceColumn))
print("Attendance Median:", np.median(attendanceColumn))

assignmentColumn = pd.to_numeric(dataFile['Assignments_Avg'], errors='coerce').dropna()
print("Assignment Mean:", np.mean(assignmentColumn))
print("Assignment Median:", np.median(assignmentColumn))
dataFile.head()

Attendance Mean: 75.431409455843
Attendance Median: 75.725
Assignment Mean: 74.79867276377426
Assignment Median: 74.81

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade
0,S1000,Omar,Williams,student0@university.com,Female,22,Engineering,52.29,55.03,57.82,84.22,74.06,3.99,85.90,56.09,F
1,S1001,Maria,Brown,student1@university.com,Male,18,Engineering,97.27,97.23,45.80,NaN,94.24,8.32,55.65,50.64,A
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Business,57.19,67.05,93.68,67.70,85.70,5.05,73.79,70.30,D
3,S1003,Omar,Williams,student3@university.com,Female,24,Mathematics,95.15,47.79,80.63,66.06,93.51,6.54,92.12,61.63,A
4,S1004,John,Smith,student4@university.com,Female,23,CS,54.18,46.59,78.89,96.85,83.70,5.97,68.42,66.13,F

### **1.3.2 Filling Missing Values Using Mean**

After performing statistical analysis, it was decided to fill the missing values using the **mean** for both affected columns, as the data was found to be approximately symmetric and not significantly dispersed.

The mean values selected for filling the missing data are:

- **Attendance (%) → 75.43**
- **Assignments_Avg → 74.80**

This approach was implemented directly within the notebook by iterating through the dataset and replacing any missing values in the specified columns with their corresponding mean values.

Using the mean ensures that the dataset remains complete and consistent while preserving the overall statistical characteristics of the data, without introducing unnecessary bias.

In [4]:
meanValueOfAttendance = 75.43
meanValueOfAssignment = 74.80

for i in range(len(dataFile['Attendance (%)'])):
    if pd.isnull(dataFile['Attendance (%)'][i]):
        dataFile.at[i, 'Attendance (%)'] = meanValueOfAttendance

for i in range(len(dataFile['Assignments_Avg'])):
    if pd.isnull(dataFile['Assignments_Avg'][i]):
        dataFile.at[i, 'Assignments_Avg'] = meanValueOfAssignment

dataFile.to_csv("ProcessedStudentDataFile.csv", index=False)
dataFile.head()

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade
0,S1000,Omar,Williams,student0@university.com,Female,22,Engineering,52.29,55.03,57.82,84.22,74.06,3.99,85.90,56.09,F
1,S1001,Maria,Brown,student1@university.com,Male,18,Engineering,97.27,97.23,45.80,74.80,94.24,8.32,55.65,50.64,A
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Business,57.19,67.05,93.68,67.70,85.70,5.05,73.79,70.30,D
3,S1003,Omar,Williams,student3@university.com,Female,24,Mathematics,95.15,47.79,80.63,66.06,93.51,6.54,92.12,61.63,A
4,S1004,John,Smith,student4@university.com,Female,23,CS,54.18,46.59,78.89,96.85,83.70,5.97,68.42,66.13,F

### **1.3.3 Participation Score Normalization**

In this step, the **Participation_Score** is normalized to ensure consistency with other score-based attributes in the dataset. Unlike other scores, which are already expressed as percentages, the Participation_Score is originally recorded on a **0–10 scale**.

To convert it into a percentage format, each value in the Participation_Score column is divided by 10 and multiplied by 100. This transformation brings the Participation_Score onto a **0–100 scale**, making it directly comparable with other numeric score features.

Additionally, a lower bound is applied using a clipping operation to ensure that the normalized Participation_Score does not fall below 1. This step helps maintain valid score values and prevents extremely low or zero values after normalization.

After normalization, the updated dataset is saved, ensuring that all score-related features are standardized and ready for further analysis or machine learning tasks.

In [5]:
dataFile['Participation_Score'] = (dataFile['Participation_Score'] / 10) * 100
dataFile['Participation_Score'] = dataFile['Participation_Score'].clip(lower=1)

dataFile.to_csv("ProcessedStudentDataFile.csv", index=False)
dataFile.head()

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade
0,S1000,Omar,Williams,student0@university.com,Female,22,Engineering,52.29,55.03,57.82,84.22,74.06,39.9,85.90,56.09,F
1,S1001,Maria,Brown,student1@university.com,Male,18,Engineering,97.27,97.23,45.80,74.80,94.24,83.2,55.65,50.64,A
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Business,57.19,67.05,93.68,67.70,85.70,50.5,73.79,70.30,D
3,S1003,Omar,Williams,student3@university.com,Female,24,Mathematics,95.15,47.79,80.63,66.06,93.51,65.4,92.12,61.63,A
4,S1004,John,Smith,student4@university.com,Female,23,CS,54.18,46.59,78.89,96.85,83.70,59.7,68.42,66.13,F

### **1.3.4 Total Score Calculation**

After normalizing all score-related attributes, the next step is to calculate the **Total_Score** for each student using a predefined assessment scheme. This weighted scoring approach ensures that each academic component contributes proportionally to the final evaluation.

The total score is computed by applying the following weight distribution:

- **Attendance:** 5%  
- **Participation_Score:** 5%  
- **Quizzes_Avg:** 5%  
- **Assignments_Avg:** 10%  
- **Projects_Score:** 15%  
- **Midterm_Score:** 20%  
- **Final_Score:** 40%  

Each component score is multiplied by its respective weight, and the weighted values are summed to obtain the final **Total_Score**. This calculation provides a fair and standardized measure of overall student performance and serves as the basis for subsequent grading and machine learning processes.

In [6]:
attendance = dataFile['Attendance (%)']
assignmentColumn = dataFile['Assignments_Avg']
quizColumn = dataFile['Quizzes_Avg']
midtermColumn = dataFile['Midterm_Score']
finaltermColumn = dataFile['Final_Score']
project_score = dataFile['Projects_Score']
participation_score = dataFile['Participation_Score']

dataFile['Total_Score'] = (
    (assignmentColumn/100)*10 +
    (quizColumn/100)*5 +
    (midtermColumn/100)*20 +
    (finaltermColumn/100)*40 +
    (attendance/100)*5 +
    (participation_score/100)*5 +
    (project_score/100)*15
)

dataFile.to_csv("ProcessedStudentDataFile.csv", index=False)
dataFile.head()

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade
0,S1000,Omar,Williams,student0@university.com,Female,22,Engineering,52.29,55.03,57.82,84.22,74.06,39.9,85.90,63.7535,F
1,S1001,Maria,Brown,student1@university.com,Male,18,Engineering,97.27,97.23,45.80,74.80,94.24,83.2,55.65,67.3290,A
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Business,57.19,67.05,93.68,67.70,85.70,50.5,73.79,78.3900,D
3,S1003,Omar,Williams,student3@university.com,Female,24,Mathematics,95.15,47.79,80.63,66.06,93.51,65.4,92.12,74.9370,A
4,S1004,John,Smith,student4@university.com,Female,23,CS,54.18,46.59,78.89,96.85,83.70,59.7,68.42,70.7010,F

### **1.3.5 Grading Scheme**

After calculating the total score for each student, the next step is to convert these percentage-based scores into **letter grades** using a predefined grading scheme. This grading scheme ensures a standardized and fair evaluation of student performance.

The following grading criteria were used to assign grades based on the calculated **Total_Score**:

| Grade | Equivalent Percentage |
|------|-----------------------|
| A    | 85 – 100              |
| A-   | 80 – 84.99            |
| B+   | 75 – 79.99            |
| B    | 71 – 74.99            |
| B-   | 68 – 70.99            |
| C    | 61 – 67.99            |
| D    | 55 – 60.99            |
| F    | Below 55              |

The script iterates through the **Total_Score** of each student and assigns a corresponding grade based on the defined percentage ranges. This step finalizes the academic evaluation process and prepares the dataset for further analysis and machine learning tasks.

In [7]:
for i in range(len(dataFile['Total_Score'])):
    score = dataFile['Total_Score'][i]
    if score >= 85:
        dataFile.at[i, 'Grade'] = 'A'
    elif score >= 80:
        dataFile.at[i, 'Grade'] = 'A-'
    elif score >= 75:
        dataFile.at[i, 'Grade'] = 'B+'
    elif score >= 71:
        dataFile.at[i, 'Grade'] = 'B'
    elif score >= 68:
        dataFile.at[i, 'Grade'] = 'B-'
    elif score >= 61:
        dataFile.at[i, 'Grade'] = 'C'
    elif score > 55:
        dataFile.at[i, 'Grade'] = 'D'
    else:
        dataFile.at[i, 'Grade'] = 'F'

dataFile.to_csv("ProcessedStudentDataFile.csv", index=False)
dataFile.head()

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade
0,S1000,Omar,Williams,student0@university.com,Female,22,Engineering,52.29,55.03,57.82,84.22,74.06,39.9,85.90,63.7535,C
1,S1001,Maria,Brown,student1@university.com,Male,18,Engineering,97.27,97.23,45.80,74.80,94.24,83.2,55.65,67.3290,C
2,S1002,Ahmed,Jones,student2@university.com,Male,24,Business,57.19,67.05,93.68,67.70,85.70,50.5,73.79,78.3900,B+
3,S1003,Omar,Williams,student3@university.com,Female,24,Mathematics,95.15,47.79,80.63,66.06,93.51,65.4,92.12,74.9370,B
4,S1004,John,Smith,student4@university.com,Female,23,CS,54.18,46.59,78.89,96.85,83.70,59.7,68.42,70.7010,B-

### **1.4 Encoding Categorical Data**

Encoding categorical data is the process of converting non-numeric (categorical) values into numeric representations so that they can be processed by statistical analysis techniques and machine learning algorithms. Since most machine learning models require numerical input, this step is essential for effective model training and evaluation.

In this dataset, the following categorical attributes were encoded:

#### **1.4.1 Gender Encoding**
The **Gender** attribute was converted into numeric values using the following mapping:

- **Female → 0**
- **Male → 1**

This conversion transforms categorical gender values into a numeric format suitable for analysis and machine learning tasks.

---

#### **1.4.2 Grade Encoding**
The **Grade** attribute consists of eight categorical values. These grades were encoded into numeric values according to their academic ranking, as shown below:

| Grade | Encoded Numeric Value |
|------|------------------------|
| A    | 1 |
| A-   | 2 |
| B+   | 3 |
| B    | 4 |
| B-   | 5 |
| C    | 6 |
| D    | 7 |
| F    | 8 |

This numeric encoding preserves the relative order of grades and enables their use in machine learning models.

---

#### **1.4.3 Department Encoding**
The **Department** attribute contains four unique categories, each of which was mapped to a numeric value:

| Department    | Encoded Value |
|--------------|---------------|
| Business     | 0 |
| CS           | 1 |
| Engineering  | 2 |
| Mathematics  | 3 |

The department encoding was generated dynamically to ensure flexibility and consistency with the dataset.

After encoding, all categorical attributes were successfully transformed into numeric form, making the dataset fully compatible with machine learning algorithms.

In [8]:
gender_map = {"Female": 0, "Male": 1}
dataFile['Gender'] = dataFile['Gender'].map(gender_map)

grade_map = {"A":1,"A-":2,"B+":3,"B":4,"B-":5,"C":6,"D":7,"F":8}
dataFile['Grade'] = dataFile['Grade'].map(grade_map)

dept_map = {}
departments = sorted(dataFile['Department'].dropna().unique())
for i in range(len(departments)):
    dept_map[departments[i]] = i

dataFile['Department'] = dataFile['Department'].map(dept_map)

dataFile.to_csv("ProcessedStudentDataFile.csv", index=False)

dataFile.head()

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade
0,S1000,Omar,Williams,student0@university.com,0,22,2,52.29,55.03,57.82,84.22,74.06,39.9,85.90,63.7535,6
1,S1001,Maria,Brown,student1@university.com,1,18,2,97.27,97.23,45.80,74.80,94.24,83.2,55.65,67.3290,6
2,S1002,Ahmed,Jones,student2@university.com,1,24,0,57.19,67.05,93.68,67.70,85.70,50.5,73.79,78.3900,3
3,S1003,Omar,Williams,student3@university.com,0,24,3,95.15,47.79,80.63,66.06,93.51,65.4,92.12,74.9370,4
4,S1004,John,Smith,student4@university.com,0,23,1,54.18,46.59,78.89,96.85,83.70,59.7,68.42,70.7010,5

### **1.5 Splitting the Data for Machine Learning**

Splitting the dataset is a standard and essential step in machine learning. It involves dividing the data into **training** and **testing** sets to evaluate how well a model performs on unseen data.

#### **1.5.1 Training Set**
- Used to train the machine learning model.
- Typically consists of **80%** of the total dataset.

#### **1.5.2 Testing Set**
- Used to evaluate the performance of the trained model.
- Typically consists of the remaining **20%** of the dataset.

#### **1.5.3 Purpose of Data Splitting**
- Ensures that the model generalizes well to new, unseen data.
- Helps prevent **overfitting**, a condition where a model performs well on training data but poorly on testing data.

By using this 80/20 data splitting approach, the model can be trained and evaluated in a controlled and reliable manner.

In [9]:
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(
    dataFile, test_size=0.2, random_state=42
)

print("Training size:", len(train_data))
print("Testing size:", len(test_data))
dataFile.head()

Training size: 4000
Testing size: 1000

,Student_ID,First_Name,Last_Name,Email,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score,Total_Score,Grade
0,S1000,Omar,Williams,student0@university.com,0,22,2,52.29,55.03,57.82,84.22,74.06,39.9,85.90,63.7535,6
1,S1001,Maria,Brown,student1@university.com,1,18,2,97.27,97.23,45.80,74.80,94.24,83.2,55.65,67.3290,6
2,S1002,Ahmed,Jones,student2@university.com,1,24,0,57.19,67.05,93.68,67.70,85.70,50.5,73.79,78.3900,3
3,S1003,Omar,Williams,student3@university.com,0,24,3,95.15,47.79,80.63,66.06,93.51,65.4,92.12,74.9370,4
4,S1004,John,Smith,student4@university.com,0,23,1,54.18,46.59,78.89,96.85,83.70,59.7,68.42,70.7010,5

## **Step 2: Machine Learning Models**

In this phase, multiple **classification algorithms** are applied to predict student grades using the processed dataset. The main objective is to evaluate and compare different machine learning models using standard performance metrics and then select the best-performing model for potential deployment.

The models are evaluated using the following metrics:

- **Accuracy** – Measures the overall correctness of the model.
- **Precision** – Indicates how many of the predicted class labels are actually correct.
- **Recall** – Measures how effectively the model identifies all relevant instances.
- **F1-Score** – The harmonic mean of precision and recall, providing a balanced measure of model performance.

The following classification algorithms are used in this analysis:

### **Decision Tree**
A Decision Tree classifier works by recursively splitting the dataset based on feature values. Each internal node represents a decision rule, while the leaf nodes represent class labels. Decision Trees are easy to interpret and can handle both numerical and categorical data effectively.

### **Random Forest**
Random Forest is an ensemble learning technique that combines multiple Decision Trees to improve prediction accuracy and reduce overfitting. Each tree is trained on a random subset of the data and features, and the final prediction is determined through majority voting.

### **Logistic Regression**
Logistic Regression is a statistical classification algorithm that models the probability of a categorical outcome. It performs well when there is a linear relationship between features and the target variable and serves as a strong baseline model for comparison.

### **Support Vector Machine (SVM)**
Support Vector Machines classify data by finding an optimal hyperplane that maximizes the margin between different classes. SVMs are particularly effective in high-dimensional feature spaces and perform well when the classes are clearly separable.

---

### **2.1 Feature Selection and Target Variable**

Before training the machine learning models, the dataset is divided into **features** and a **target variable**.

- The **feature set (X)** contains all relevant academic attributes used for prediction.
- The **target variable (y)** represents the output label to be predicted, which is the **Grade**.

Non-predictive and identifier attributes such as student IDs and personal information are removed to ensure that the models learn only from meaningful academic data. In addition, the **Total_Score** column is excluded from the feature set because grades are already derived from this value. Including Total_Score as an input feature would introduce **data leakage** and result in misleading model performance.

By removing the **Total_Score** column, the model is trained to predict grades based solely on individual academic components, leading to a more realistic and reliable learning process.

In [10]:
df = pd.read_csv("ProcessedStudentDataFile.csv")

X = df.drop(columns=['Student_ID', 'First_Name', 'Last_Name', 'Email', 'Grade','Total_Score' ])
y = df['Grade']

X.head()

,Gender,Age,Department,Attendance (%),Midterm_Score,Final_Score,Assignments_Avg,Quizzes_Avg,Participation_Score,Projects_Score
0,0,22,2,52.29,55.03,57.82,84.22,74.06,39.9,85.90
1,1,18,2,97.27,97.23,45.80,74.80,94.24,83.2,55.65
2,1,24,0,57.19,67.05,93.68,67.70,85.70,50.5,73.79
3,0,24,3,95.15,47.79,80.63,66.06,93.51,65.4,92.12
4,0,23,1,54.18,46.59,78.89,96.85,83.70,59.7,68.42

### **2.2 Train–Test Split and Feature Scaling**

In this step, the dataset is divided into **training** and **testing** sets to evaluate the performance of machine learning models on unseen data. An **80/20 split** is used, where 80% of the data is allocated for training and 20% for testing. A fixed random state is applied to ensure reproducibility of results.

After splitting the data, **feature scaling** is performed for models that are sensitive to the scale of input features, specifically **Logistic Regression** and **Support Vector Machine (SVM)**.

Standardization is applied using the **StandardScaler**, which transforms the features to have:
- A mean of 0  
- A standard deviation of 1  

This step ensures that all features contribute equally to the model training process and prevents features with larger numeric ranges from dominating the learning process.

The scaled feature sets are used for Logistic Regression and SVM, while unscaled features may be used for tree-based models such as Decision Trees and Random Forests.

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=47
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### **2.3 Model Initialization**

In this step, multiple **classification models** are initialized to perform a comparative analysis of different machine learning algorithms. Initializing the models in advance allows for a consistent and systematic training and evaluation process.

The following classifiers are used in this study:

- **Decision Tree Classifier:**  
  A tree-based model that makes decisions by splitting data based on feature values. It is simple to interpret and effective for capturing non-linear relationships.

- **Random Forest Classifier:**  
  An ensemble learning technique that combines multiple decision trees to improve prediction accuracy and reduce overfitting.

- **Logistic Regression:**  
  A statistical classification model that estimates the probability of class membership. It performs well on linearly separable data and serves as a strong baseline model.

- **Support Vector Machine (SVM):**  
  A powerful classifier that identifies the optimal hyperplane to separate different classes by maximizing the margin between them.

A fixed random state is applied where applicable to ensure reproducibility of the results.

In [12]:
models = {
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'SVM': SVC(random_state=42)
}

### **2.4 Model Training, Prediction, and Evaluation**

In this step, all initialized machine learning models are trained, tested, and evaluated using the same dataset split to ensure a fair comparison. Each model is trained on the training data and then used to predict the class labels for the test data.

For models that are sensitive to feature scaling, specifically **Logistic Regression** and **Support Vector Machine (SVM)**, the scaled training and testing datasets are used. Tree-based models such as **Decision Tree** and **Random Forest** are trained using the original unscaled feature values, as they are not affected by feature scaling.

After generating predictions, each model is evaluated using the following performance metrics:

- **Accuracy:** Measures the overall correctness of the model.
- **Precision:** Indicates how many of the predicted class labels are correct.
- **Recall:** Measures the model’s ability to correctly identify all relevant instances.
- **F1-Score:** The harmonic mean of precision and recall, providing a balanced performance measure.

The evaluation results are stored in a structured format and presented in a comparative table for analysis.

In [13]:
results = {}

for name, model in models.items():
    if name in ['Logistic Regression', 'SVM']:
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

    results[name] = {
        'Accuracy': accuracy_score(y_test, y_pred),
        'Precision': precision_score(y_test, y_pred, average='weighted'),
        'Recall': recall_score(y_test, y_pred, average='weighted'),
        'F1-Score': f1_score(y_test, y_pred, average='weighted')
    }

results_df = pd.DataFrame(results).T
results_df

                     Accuracy  Precision  Recall  F1-Score
Decision Tree           0.590   0.591445   0.590  0.590036
Random Forest           0.709   0.704260   0.709  0.695435
Logistic Regression     0.924   0.927164   0.924  0.922290
SVM                     0.878   0.878595   0.878  0.876215

### **2.5 Best Model Selection for Deployment**

After evaluating all classification models using accuracy, precision, recall, and F1-score, the final step is to select the most suitable model for deployment. These evaluation metrics together provide a comprehensive view of each model’s performance.

Based on the comparative analysis of all metrics, **Logistic Regression** consistently achieved the highest overall performance among the tested models.

Therefore, **Logistic Regression** was selected as the best model for deployment, as it demonstrated strong predictive performance and reliable generalization on unseen data.

In [14]:
best_model_name = results_df['F1-Score'].idxmax()
print("Best model for deployment:", best_model_name)

Best model for deployment: Logistic Regression

### **Conclusion**

In this Phase, we complete end-to-end data preprocessing and machine learning pipeline was implemented to analyze and predict student academic performance. The dataset was carefully cleaned by handling missing values, normalizing numeric features, applying a weighted assessment scheme, assigning grades, and encoding categorical variables to ensure compatibility with machine learning algorithms.

A logical data splitting strategy was applied to create training and testing sets, followed by the implementation of multiple classification models, including Decision Tree, Random Forest, Logistic Regression, and Support Vector Machine. These models were evaluated using standard performance metrics such as accuracy, precision, recall, and F1-score.

Based on a comparison of accuracy, precision, recall, and F1-score, **Logistic Regression** achieved the highest overall performance and was selected as the final model.

In [ ]:
# retrain_model.py
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import joblib

# Load processed CSV
df = pd.read_csv("ProcessedStudentDataFile.csv")

# Feature columns
feature_cols = ['Gender','Age','Department','Attendance (%)','Midterm_Score',
                'Final_Score','Assignments_Avg','Quizzes_Avg','Participation_Score','Projects_Score']
X = df[feature_cols]
y = df['Grade']

# Scale
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train model
model = LogisticRegression(max_iter=1000)
model.fit(X_scaled, y)

# Save model and scaler
joblib.dump(model, "ml_models/best_model.pkl")
joblib.dump(scaler, "ml_models/scaler.pkl")

print("✅ Model and scaler saved successfully")

Best model saved as 'best_model.pkl' ✅